language: php

php:
- 7

matrix:
  fast_finish: true
  include:
    - php: 7
      env: TYPO3_VERSION=^8.7.0 COVERAGE=1
    - php: 7
      env: TYPO3_VERSION=dev-master COVERAGE=0
  allow_failures:
    - env: TYPO3_VERSION=dev-master COVERAGE=0

sudo: false
cache:
  directories:
    - $HOME/.composer/cache

before_install:
- |
  if [[ "$COVERAGE" == "0" ]]; then
    phpenv config-rm xdebug.ini
  fi;
- composer self-update
- composer --version

before_script:
- composer require typo3/cms=$TYPO3_VERSION
- export TYPO3_PATH_WEB="$PWD/.Build/Web"

script:
- |
  composer phpunit || true
- |
  composer phpmd || true
- |
  composer phpcs || true

after_script:
- |
  if [[ "$COVERAGE" == "1" ]]; then
    echo; echo "Uploading code coverage results";
    .Build/bin/ocular code-coverage:upload --format=php-clover .Build/unittest-coverage.clover
  fi
