language: php

php:
- 5.6
- 7

env:
- TYPO3_VERSION=^6.2.0 COVERAGE=0
- TYPO3_VERSION=^7.6.0 COVERAGE=0
matrix:
  fast_finish: true
  exclude:
    - php: 7
      env: TYPO3_VERSION=^6.2.0 COVERAGE=0
    - php: 7
      env: TYPO3_VERSION=^7.6.0 COVERAGE=0
  include:
    - php: 7
      env: TYPO3_VERSION=^7.6.0 COVERAGE=1
    - php: 7
      env: TYPO3_VERSION=^8.5.0 COVERAGE=0
    - php: 7
      env: TYPO3_VERSION=dev-master COVERAGE=0
  allow_failures:
    - env: TYPO3_VERSION=dev-master COVERAGE=0

sudo: false
cache:
  directories:
    - $HOME/.composer/cache

before_install:
- |
  if [[ "$COVERAGE" == "0" ]]; then
    phpenv config-rm xdebug.ini
  fi;
- composer self-update
- composer --version

before_script:
- composer require typo3/cms=$TYPO3_VERSION
- export TYPO3_PATH_WEB="$PWD/.Build/Web"

script:
- |
  echo; echo "Running unit tests";
  if [[ "$COVERAGE" == "1" ]]; then
    .Build/bin/phpunit -c Tests/UnitTests.xml --coverage-clover=.Build/unittest-coverage.clover
  else
    .Build/bin/phpunit -c Tests/UnitTests.xml
  fi;
- |
  echo; echo "Executing PHP mess detector"; .Build/bin/phpmd Classes/ text cleancode,codesize,controversial,design,naming || true
- |
  echo; echo "Executing PHP code sniffer"; .Build/bin/phpcs --runtime-set ignore_warnings_on_exit true --standard=PSR2 Classes/

after_script:
- |
  if [[ "$COVERAGE" == "1" ]]; then
    echo; echo "Uploading code coverage results";
    .Build/bin/ocular code-coverage:upload --format=php-clover .Build/unittest-coverage.clover
  fi
