services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  SFC\Staticfilecache\:
    resource: '../Classes/*'

  SFC\Staticfilecache\EventListener\AfterPackageDeactivationListener:
    tags:
      - name: event.listener
        identifier: 'SfcAfterPackageDeactivationListener'
        event: TYPO3\CMS\Core\Package\Event\AfterPackageDeactivationEvent
