name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: pxgamer/composer-action@master
        with:
          command: install --optimize-autoloader --prefer-dist
