name: Test
on: [push,pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.0', '8.1', '8.2' ]
        typo3: [ '11', '12' ]
        exclude:
          - php: '8.0'
            typo3: '12'
    steps:
      - uses: actions/checkout@v1
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: imagick
      - name: Composer install
        run: composer require typo3/minimal="^${{ matrix.typo3 }}" --dev --optimize-autoloader --prefer-dist
      - name: Composer phpstan
        run: composer phpstan
      - name: Composer test
        run: composer test
