name: Test
on: [push,pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: imagick
      - uses: pxgamer/composer-action@master
        with:
          command: install --optimize-autoloader --prefer-dist
      - uses: pxgamer/composer-action@master
        with:
          command: test
